version: '3.8'
services:
  backend:
    build: .
    command: uvicorn backend.app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app/backend
    ports:
      - '8000:8000'
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - '3000:3000'
